### PR TITLE
Questions answers

### PR DESCRIPTION
**Pull request by ChrisPadovan**
Styling, components, and features added.

### CODE REVIEW

**Review by ec-rilo — CHANGES_REQUESTED** [review]
**Important Comments**
I dig this PR! Lots of changes / additions and heavy refactoring from past Pr's. Only have a few major things to say. It looks like you're commiting an empty file to master. I think it's best to not have them there since they're not in use in the application. I also see that in `Modal.jsx` the import for `NewQuestion` component is not pointing to the correct file.

I'm also getting a "You must enter the following" message when I fill out the question popup completly but I'm not sure what to fill out and the page refreshes. Not sure if intentional.

 Screenshot from 2022-04-12 11-36-38
 
 The search feature is dope.
 
 Looks like a good chunk to push to master! The only thing I'd consider before pushing is to not have the empty file in this PR and for the import to point to the correct file in `Modal.jsx`.

**Nitpicks**

Looking at your imports some are still showing .jsx in the file. like

`import Questions from './questions.jsx` all imports should now not include the .jsx - current master branches has a webpack config that does it for us! So they should now look like this.

`import Questions from './questions`

Not sure how spread across your components this is but in `QuestionsAnswers.jsx` I'm seeing some styled components not in use anymore that could be removed. 

In `Modal.jsx` it doesn't look like the logic is within a component, I'd recommend putting a div there. It may cause unexpected behavior. Also some unused styled-components in this file.

Some easy linter fixes are in here like in `answers.jsx` there's lots of red which can be fixed with 3 lines of formatting.

**Comment by gaolbreaker** [comment]
- handleSubmit() in NewQuestion.jsx and NewAnswer.jsx needs an `event.preventDefault() `to stop the page from reloading.
- emailChecker() console.logs a null value when I enter 'sdflkj' so I don't think it's working
- From a user experience standpoint, it's not clear what the 'name' field in the modal is for. The placeholder of 'Example: jackson11!' doesn't tell the user anything.
- If a lot of "Add Answer" buttons are available, I can click on all of them and fill the page with them, often overlapping with one another (see image below)
- The Add Your Answer modal has a transparent background for some reason, so I can see the underlying page underneath the modal. The New Question modal does not have this problem.
- Clicking 'Helpful? Yes' for an answer doesn't do anything. (It works perfectly at the question level)
- From a user experience perspective, "LOAD MORE ANSWERS" shouldn't appear if there are no more answers to show. Just like how "More Answered Questions" disappears when there are no more questions to show.

Some of the above is just my opinion on user experience and might not be part of the bare minimum requirements, feel free to ignore if in your judgment there are other items to address first.

image
image

**Review by gaolbreaker — APPROVED** [review]
Not sure what the difference is between a review and a comment. This looks good to me, but see my comments in my... comment.

**Comment by ec-rilo** [comment]
Just a headsup - leaving this up for a bit so we can see comments but will close tomorrow

**Pull request closed without merging**
