### PR TITLE
Feat/related items

### PR DESCRIPTION
**Pull request by gaolbreaker**
Address Edgar's comments from previous closed PR

### CODE REVIEW

**Comment by gaolbreaker** [comment]
I forgot to fix the unique key issue for the .map invocation in Compare.jsx

**Comment by gaolbreaker** [comment]
@ec-rilo Are you pulling down the most recent changes? I had already fixed the unique key warning without using uniqid.

image
image

I haven't figured out the "Reduce of empty array with no initial value" bug yet--still working on it.
I think the 200 classes thing comes from your stars component, which I'm using to render stars.

image

^ I had deleted the console.log in line 101 of the screenshot you included of YourOutfit.jsx but kept the one on line 97 in your screenshot because I thought it was useful to indicate somehow that there is an attempt to add a duplicate entry. I'll delete it for the sake of console hygiene later.

image

^ I had already eliminated the .jsx extensions yesterday, I believe. Again, I believe you're looking at an older commit for some reason.

Some to-dos that I'm aware of that are on the back-burner include:
- Eliminating nested ternary expressions
- Transitioning all the styling to styled-components
- I squelched some of the propTypes issues by getting rid of "isRequired," which is not the ideal or perfect solution, but I have been prioritizing functionality over syntactic purity (and pretty much always will)
- I haven't had time to fully detail/specify the arrays and objects in propTypes for the same reason, but will get to it at a later point in time.

**Comment by ec-rilo** [comment]
Gotta love github, going to checkout it out tomorrow morning - I agree for the console.log on line 101 I liked it there

**Review by ChrisPadovan — APPROVED** [review]
Massive update! Works and looks good to me, approved.

**Pull request merged**
