### PR TITLE
Feat/stars list component

### PR DESCRIPTION
**Pull request by ec-rilo**
This PR adds
1. A Star Component
2. A StarList Component
3. A reviews redirect component
4. A component that combines the Reviews Redirect and Stars List component.

A nifty thing that I added is some documentation to Star and StarList components to help understand how to use them.

The stars are flexible enough to be able to be used anywhere on the website!

### CODE REVIEW

**Review by alimeow — APPROVED** [review]
Awesome. Can't wait to try it out.

**Review by gaolbreaker — COMMENTED** [review]
Line 5 and Line 22 of ReviewsRedirect.jsx specify that `className` be passed in, but in StarsListAndReviews.jsx on line 15 `className` is in a surrounding div instead of on `<StyledReviewsRedirect />` directly. How does it have access to className? Or is there something I'm missing?

**Review by ChrisPadovan — APPROVED** [review]
Just read through all of it, nice job on formatting and comments. I also appreciate the names you used on your components. Approved!

**Comment by ec-rilo** [comment]
> Line 5 and Line 22 of ReviewsRedirect.jsx specify that `className` be passed in, but in StarsListAndReviews.jsx on line 15 `className` is in a surrounding div instead of on `<StyledReviewsRedirect />` directly. How does it have access to className? Or is there something I'm missing?

So className is only in reference to the styled-component. It's pretty much saying "Hey! this component has a class called 'className' that it can use. You're able to add this class to any element within this."

As styled-components are used more it makes more sense.

**Pull request merged**
