### PR TITLE
Feat/related items

### PR DESCRIPTION
**Pull request by gaolbreaker**
My component is able to now display "related items" reliably. For now, pass in the current product ID as a prop. If nothing is passed in, a random item will be shown instead. There is a small testing dashboard at the bottom that allows you to view what the component currently considers to be the "current product."

Still need to work on the carousel functionality, the modal, and the Your Outfit (i.e., favorites).

Everything is in one file. I have ignored "separation of concerns" and other nice-to-haves for now and will refactor later.

### CODE REVIEW

**Review by ec-rilo — COMMENTED** [review]
Not sure why this change was made? I'm assuming the original .gitignore would prevent the dist folder from being tracked but it's changed to go for the specific file in dist `config.js`?

**Comment by ec-rilo** [comment]
Also it sounds like some of what you have is test code not final code. With some comments like "There is a small testing dashboard at the bottom" and a good chunk of the code in one file which doesn't sound like what would be your final implementation.

I don't think we should be pushing test code / non-finalized code to master since debugging one file that has multiple different concerns would make it difficult to find a bug.

I'd say it'd be nice to see smaller commits that describe what the commit is doing instead of a broad "Made changes to suggestions.jsx" commit message which makes it difficult to see what exact change was made in the file.

**Review by ec-rilo — CHANGES_REQUESTED** [review]
What I'm seeing is not final code. With some comments like "There is a small testing dashboard at the bottom" and a good chunk of the code in one file which doesn't sound like what would be your final implementation. Unless the intention is for all of it to be in one file?

I don't think we should be pushing test code / non-finalized code to master since debugging one file that has multiple different concerns would make it difficult to find a bug.

I'd say it'd be nice to see smaller commits that describe what the commit is doing instead of a broad "Made changes to suggestions.jsx" commit message which makes it difficult to see what exact change was made in the file.

I'd say it'd be best to close this pr and seeing a new one with smaller more specifc commit messages with separation of concerns. + Some reasons for changes for things like the .gitignore file addition.

That way we can just do cleanup and review on your more finialized looking commits. Instead of taking a look at non-finalized components.

**Comment by gaolbreaker** [comment]
Closing PR. Will implement suggestions and come back again later. Thanks!

**Pull request closed without merging**
